function result = apiGetMetadata(type)
% APIGETMETADATA API接口：获取算法或基准函数的元数据
%
% 输入参数:
%   type - 元数据类型: 'algorithms' | 'benchmarks' | 'all'
%
% 输出参数:
%   result - JSON格式的元数据字符串
%
% 示例:
%   result = apiGetMetadata('algorithms');
%   algorithms = jsondecode(result);
%
%   result = apiGetMetadata('benchmarks');
%   benchmarks = jsondecode(result);
%
%   result = apiGetMetadata('all');
%   metadata = jsondecode(result);
%   algorithms = metadata.algorithms;
%   benchmarks = metadata.benchmarks;

    switch type
        case 'algorithms'
            data = getAlgorithmMetadata();
        case 'benchmarks'
            data = getBenchmarkMetadata();
        case 'all'
            data = struct(...
                'algorithms', {getAlgorithmMetadata()}, ...
                'benchmarks', {getBenchmarkMetadata()} ...
            );
        otherwise
            error('API:InvalidType', '无效的类型 "%s"。请使用: algorithms, benchmarks, 或 all', type);
    end

    result = jsonencode(data);
end

function algorithms = getAlgorithmMetadata()
% GETALGORITHMMETADATA 返回所有可用算法的元数据列表

    % 算法定义列表
    algorithms = {
        struct(...
            'id', 'GWO', ...
            'name', 'GWO', ...
            'fullName', 'Grey Wolf Optimizer', ...
            'version', '2.0.0', ...
            'description', '灰狼优化器，模拟灰狼群体的领导层级和狩猎行为', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'ALO', ...
            'name', 'ALO', ...
            'fullName', 'Ant Lion Optimizer', ...
            'version', '2.0.0', ...
            'description', '蚁狮优化器，模拟蚁狮幼虫捕食蚂蚁的行为', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'WOA', ...
            'name', 'WOA', ...
            'fullName', 'Whale Optimization Algorithm', ...
            'version', '2.0.0', ...
            'description', '鲸鱼优化算法，模拟座头鲸的气泡网捕食策略', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'b', struct('type', 'float', 'default', 1, 'min', 0, 'description', '螺旋参数') ...
            ) ...
        );
        struct(...
            'id', 'IGWO', ...
            'name', 'IGWO', ...
            'fullName', 'Improved Grey Wolf Optimizer', ...
            'version', '2.0.0', ...
            'description', '改进灰狼优化器，引入距离学习启发式搜索机制', ...
            'category', 'hybrid', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 10, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'EWOA', ...
            'name', 'EWOA', ...
            'fullName', 'Enhanced Whale Optimization Algorithm', ...
            'version', '2.0.0', ...
            'description', '增强鲸鱼优化算法，引入汇聚机制和Cauchy分布', ...
            'category', 'hybrid', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'b', struct('type', 'float', 'default', 1, 'min', 0, 'description', '螺旋参数'), ...
                'poolKappa', struct('type', 'float', 'default', 1.5, 'min', 1, 'description', '汇聚池大小倍数'), ...
                'portionRate', struct('type', 'integer', 'default', 20, 'min', 1, 'description', '迁移比例数量') ...
            ) ...
        );
        struct(...
            'id', 'DA', ...
            'name', 'DA', ...
            'fullName', 'Dragonfly Algorithm', ...
            'version', '2.0.0', ...
            'description', '蜻蜓算法，模拟蜻蜓静态和动态群集行为', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'separationWeight', struct('type', 'float', 'default', 0.1, 'min', 0, 'description', '分离权重'), ...
                'alignmentWeight', struct('type', 'float', 'default', 0.1, 'min', 0, 'description', '对齐权重'), ...
                'cohesionWeight', struct('type', 'float', 'default', 0.1, 'min', 0, 'description', '凝聚权重'), ...
                'foodWeight', struct('type', 'float', 'default', 0.1, 'min', 0, 'description', '食物吸引权重'), ...
                'enemyWeight', struct('type', 'float', 'default', 0.1, 'min', 0, 'description', '敌人排斥权重') ...
            ) ...
        );
        struct(...
            'id', 'BDA', ...
            'name', 'BDA', ...
            'fullName', 'Binary Dragonfly Algorithm', ...
            'version', '2.0.0', ...
            'description', '二进制蜻蜓算法，使用V3传递函数进行二进制优化', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'BBA', ...
            'name', 'BBA', ...
            'fullName', 'Binary Bat Algorithm', ...
            'version', '2.0.0', ...
            'description', '二进制蝙蝠算法，使用V型传递函数', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 20, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'Qmin', struct('type', 'float', 'default', 0, 'description', '最小频率'), ...
                'Qmax', struct('type', 'float', 'default', 2, 'description', '最大频率'), ...
                'loudness', struct('type', 'float', 'default', 0.5, 'min', 0, 'max', 1, 'description', '响度'), ...
                'pulseRate', struct('type', 'float', 'default', 0.5, 'min', 0, 'max', 1, 'description', '脉冲率') ...
            ) ...
        );
        struct(...
            'id', 'GA', ...
            'name', 'GA', ...
            'fullName', 'Genetic Algorithm', ...
            'version', '2.0.0', ...
            'description', '遗传算法，模拟自然选择和遗传机制', ...
            'category', 'evolutionary', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 50, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'crossoverRate', struct('type', 'float', 'default', 0.8, 'min', 0, 'max', 1, 'description', '交叉概率'), ...
                'mutationRate', struct('type', 'float', 'default', 0.01, 'min', 0, 'max', 1, 'description', '变异概率'), ...
                'eliteCount', struct('type', 'integer', 'default', 2, 'min', 0, 'description', '精英个体数量') ...
            ) ...
        );
        struct(...
            'id', 'SA', ...
            'name', 'SA', ...
            'fullName', 'Simulated Annealing', ...
            'version', '2.0.0', ...
            'description', '模拟退火算法，模拟金属退火过程', ...
            'category', 'physics', ...
            'paramSchema', struct(...
                'maxIterations', struct('type', 'integer', 'default', 1000, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'initialTemp', struct('type', 'float', 'default', 100, 'min', 0, 'description', '初始温度'), ...
                'finalTemp', struct('type', 'float', 'default', 0.01, 'min', 0, 'description', '终止温度'), ...
                'coolingRate', struct('type', 'float', 'default', 0.95, 'min', 0, 'max', 1, 'description', '冷却速率') ...
            ) ...
        );
        struct(...
            'id', 'VPSO', ...
            'name', 'VPSO', ...
            'fullName', 'Variable Velocity PSO', ...
            'version', '2.0.0', ...
            'description', '变速度粒子群优化算法', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'VPPSO', ...
            'name', 'VPPSO', ...
            'fullName', 'Variable Parameter PSO', ...
            'version', '2.0.0', ...
            'description', '变参数粒子群优化算法', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'WOASA', ...
            'name', 'WOA-SA', ...
            'fullName', 'WOA-SA Hybrid Algorithm', ...
            'version', '2.0.0', ...
            'description', '鲸鱼优化与模拟退火混合算法', ...
            'category', 'hybrid', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 5, 'max', 10000, 'description', '种群大小'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
        struct(...
            'id', 'MFO', ...
            'name', 'MFO', ...
            'fullName', 'Moth-Flame Optimization', ...
            'version', '2.0.0', ...
            'description', '飞蛾火焰优化算法，模拟飞蛾横向导航行为', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 10, 'max', 10000, 'description', '飞蛾种群数量'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'b', struct('type', 'float', 'default', 1, 'min', 0, 'max', 10, 'description', '对数螺旋形状常数') ...
            ) ...
        );
        struct(...
            'id', 'MVO', ...
            'name', 'MVO', ...
            'fullName', 'Multi-Verse Optimizer', ...
            'version', '2.0.0', ...
            'description', '多元宇宙优化算法，模拟宇宙中白洞、黑洞和虫洞机制', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 10, 'max', 10000, 'description', '宇宙种群数量'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'WEP_Min', struct('type', 'float', 'default', 0.2, 'min', 0, 'max', 1, 'description', '最小虫洞存在概率'), ...
                'WEP_Max', struct('type', 'float', 'default', 1.0, 'min', 0, 'max', 1, 'description', '最大虫洞存在概率') ...
            ) ...
        );
        struct(...
            'id', 'SCA', ...
            'name', 'SCA', ...
            'fullName', 'Sine Cosine Algorithm', ...
            'version', '2.0.0', ...
            'description', '正弦余弦算法，基于正弦和余弦函数的优化方法', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 10, 'max', 10000, 'description', '搜索代理数量'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数'), ...
                'a', struct('type', 'float', 'default', 2, 'min', 0, 'max', 10, 'description', '控制探索/开发平衡参数') ...
            ) ...
        );
        struct(...
            'id', 'SSA', ...
            'name', 'SSA', ...
            'fullName', 'Salp Swarm Algorithm', ...
            'version', '2.0.0', ...
            'description', '樽海鞘群算法，模拟樽海鞘群体链状行为', ...
            'category', 'swarm', ...
            'paramSchema', struct(...
                'populationSize', struct('type', 'integer', 'default', 30, 'min', 10, 'max', 10000, 'description', '樽海鞘种群数量'), ...
                'maxIterations', struct('type', 'integer', 'default', 500, 'min', 1, 'max', 100000, 'description', '最大迭代次数') ...
            ) ...
        );
    };
end

function benchmarks = getBenchmarkMetadata()
% GETBENCHMARKMETADATA 返回所有基准测试函数的元数据列表

    % 基准函数列表
    benchmarks = {
        % 单峰函数 F1-F7
        struct('id', 'F1', 'name', 'Sphere', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -100, 'upperBound', 100, 'optimalValue', 0, 'description', '简单的凸函数，用于测试收敛性');
        struct('id', 'F2', 'name', 'Rosenbrock', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -30, 'upperBound', 30, 'optimalValue', 0, 'description', '经典的优化测试函数');
        struct('id', 'F3', 'name', 'Step', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -100, 'upperBound', 100, 'optimalValue', 0);
        struct('id', 'F4', 'name', 'Quartic', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -1.28, 'upperBound', 1.28, 'optimalValue', 0);
        struct('id', 'F5', 'name', 'Schwefel 2.22', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -10, 'upperBound', 10, 'optimalValue', 0);
        struct('id', 'F6', 'name', 'Schwefel 1.2', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -65.536, 'upperBound', 65.536, 'optimalValue', 0);
        struct('id', 'F7', 'name', 'Schwefel 2.21', 'type', 'Unimodal', 'dimension', 30, 'lowerBound', -100, 'upperBound', 100, 'optimalValue', 0);

        % 多峰函数 F8-F13
        struct('id', 'F8', 'name', 'Schwefel', 'type', 'Multimodal', 'dimension', 30, 'lowerBound', -500, 'upperBound', 500, 'optimalValue', -12569.487, 'description', '全局最优点远离搜索空间中心');
        struct('id', 'F9', 'name', 'Rastrigin', 'type', 'Multimodal', 'dimension', 30, 'lowerBound', -5.12, 'upperBound', 5.12, 'optimalValue', 0, 'description', '高度多峰，大量局部最优');
        struct('id', 'F10', 'name', 'Ackley', 'type', 'Multimodal', 'dimension', 30, 'lowerBound', -32, 'upperBound', 32, 'optimalValue', 0, 'description', '具有几乎平坦的区域');
        struct('id', 'F11', 'name', 'Griewank', 'type', 'Multimodal', 'dimension', 30, 'lowerBound', -600, 'upperBound', 600, 'optimalValue', 0);
        struct('id', 'F12', 'name', 'Penalized 1', 'type', 'Multimodal', 'dimension', 30, 'lowerBound', -50, 'upperBound', 50, 'optimalValue', 0);
        struct('id', 'F13', 'name', 'Penalized 2', 'type', 'Multimodal', 'dimension', 30, 'lowerBound', -50, 'upperBound', 50, 'optimalValue', 0);

        % 固定维度多峰函数 F14-F23
        struct('id', 'F14', 'name', 'Shekel 5', 'type', 'Fixed-dimension Multimodal', 'dimension', 2, 'lowerBound', -65.536, 'upperBound', 65.536, 'optimalValue', 0.998);
        struct('id', 'F15', 'name', 'Kowalik', 'type', 'Fixed-dimension Multimodal', 'dimension', 4, 'lowerBound', -5, 'upperBound', 5, 'optimalValue', 0.0003075);
        struct('id', 'F16', 'name', 'Six-Hump Camel', 'type', 'Fixed-dimension Multimodal', 'dimension', 2, 'lowerBound', -5, 'upperBound', 5, 'optimalValue', -1.0316285);
        struct('id', 'F17', 'name', 'Branin', 'type', 'Fixed-dimension Multimodal', 'dimension', 2, 'lowerBound', -5, 'upperBound', 15, 'optimalValue', 0.397887);
        struct('id', 'F18', 'name', 'Goldstein-Price', 'type', 'Fixed-dimension Multimodal', 'dimension', 2, 'lowerBound', -2, 'upperBound', 2, 'optimalValue', 3);
        struct('id', 'F19', 'name', 'Hartman 3', 'type', 'Fixed-dimension Multimodal', 'dimension', 3, 'lowerBound', 0, 'upperBound', 1, 'optimalValue', -3.86);
        struct('id', 'F20', 'name', 'Hartman 6', 'type', 'Fixed-dimension Multimodal', 'dimension', 6, 'lowerBound', 0, 'upperBound', 1, 'optimalValue', -3.32);
        struct('id', 'F21', 'name', 'Shekel 7', 'type', 'Fixed-dimension Multimodal', 'dimension', 4, 'lowerBound', 0, 'upperBound', 10, 'optimalValue', -10.1532);
        struct('id', 'F22', 'name', 'Shekel 10', 'type', 'Fixed-dimension Multimodal', 'dimension', 4, 'lowerBound', 0, 'upperBound', 10, 'optimalValue', -10.4029);
        struct('id', 'F23', 'name', 'Shekel 10 (alt)', 'type', 'Fixed-dimension Multimodal', 'dimension', 4, 'lowerBound', 0, 'upperBound', 10, 'optimalValue', -10.5364);
    };
end
